# Generated by Django 5.0.7 on 2024-07-20 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('pesquisadora', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('idade', models.CharField(choices=[('16-25', '16 a 25 anos'), ('26-34', '26 a 34 anos'), ('35-55', '35 a 55 anos'), ('55+', 'Acima de 55 anos')], max_length=5)),
                ('votaria_brazao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('rede_social', models.CharField(choices=[('FB', 'Facebook'), ('WA', 'WhatsApp'), ('IG', 'Instagram'), ('TW', 'Twitter'), ('YT', 'YouTube'), ('OT', 'Outros')], max_length=2)),
                ('prioridade_prefeito', models.CharField(max_length=100)),
                ('politico_mais_fez', models.CharField(max_length=100)),
                ('votaria_presidente', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('prefeito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefeito', to='pesquisa.candidato')),
                ('vereador', models.ManyToManyField(related_name='vereador', to='pesquisa.candidato')),
            ],
        ),
    ]
